name: a11ywatch Manual Execution
on:
  workflow_dispatch:
jobs:
  a11yWatchRun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Web Accessibility Evaluation
        uses: a11ywatch/github-actions@v2.1.6
        with:
          WEBSITE_URL: https://spacetelescope.github.io/jdat_notebooks/
          SITE_WIDE: true
          SUBDOMAINS: true
          SITEMAP: true
          UPGRADE: true
          LIST: false
          EXTERNAL: false
          UPLOAD: true
