name: a11ywatch Remote Manual Execution
on:
  workflow_dispatch:
jobs:
  a11yWatchRun:
    uses: spacetelescope/notebook-ci-actions/.github/workflows/html_accessibility_check.yml@main
    with:
      target_url: 'https://spacetelescope.github.io/${{ github.event.repository.name }}/'

    
