name: a11ywatch Remote Manual Execution
on:
  workflow_dispatch:
jobs:
  a11yWatchRun:
    uses: dulude/notebook-ci-actions/.github/workflows/html_accessibility_check.yml@make_html_checker_better

    
